### ISSUE TITLE
Error when running a NodeJS program

### ISSUE THREAD

**Issue by hverlin** [134130/intellij-mise#49]
Should the plugin configure the `NodeJS` setting in IntelliJ to use the same version as `mise`?
<img width="1312" alt="image" src="https://github.com/user-attachments/assets/7f943bd3-2df4-41b4-8287-df4322215bad">

when running a Node.js program, I am also getting the following error
```
java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.putAll(ImmutableCollections.java:1080)
	at com.github.l34130.mise.runconfig.NodeRunConfigurationExtension.createLaunchSession(NodeRunConfigurationExtension.kt:40)
	at com.intellij.javascript.nodejs.execution.runConfiguration.NodeRunConfigurationExtensionsManager.createLaunchSession(NodeRunConfigurationExtensionsManager.kt:18)
	at com.jetbrains.nodejs.run.NodeJsRunProfileState.<init>(NodeJsRunProfileState.kt:38)
	at com.jetbrains.nodejs.run.NodeJsRunConfiguration.getState(NodeJsRunConfiguration.java:132)
```
seems that `config.env` is immutable

**Comment by 134130** [comment]
Actually, I tested very shallowly for NodeJS support. 😭
I'll check fully about it. Thank you for your report!

**Comment by hverlin** [comment]
Thanks, please let me know if I can help here. I am actually quite interested in having IntelliJ automatically detect the correct NodeJS to use

**Comment by 134130** [comment]
@hverlin Hi, I've added this feature in v2.2.0. It will be available in JetBrains Marketplace soon. Thanks!

**Comment by hverlin** [comment]
Thank you, adding support for automatic Node.js SDK detection here: https://github.com/134130/intellij-mise/pull/58
