### ISSUE TITLE
Unhandled exception when running task

### ISSUE THREAD

**Issue by hverlin** [134130/intellij-mise#80]
I get the following error when running a task 

```
Unhandled exception in [ComponentManager(ProjectImpl@909591185), CoroutineName(com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager), ModalityState.NON_MODAL, Dispatchers.EDT]

java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at org.jetbrains.plugins.terminal.ShellTerminalWidget.toShellJediTermWidgetOrThrow(ShellTerminalWidget.java:386)
	at org.jetbrains.plugins.terminal.TerminalView.createLocalShellWidget(TerminalView.kt:45)
	at com.github.l34130.mise.commands.MiseRunAction$Companion.executeTask$lambda$0(MiseRunAction.kt:32)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$invokeLater$1.invokeSuspend(ToolWindowManagerImpl.kt:1560)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:44)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:229)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:211)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithImplicitRead(AnyThreadWriteThreadingSupport.kt:122)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1162)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:78)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:119)
```

**Comment by 134130** [comment]
The error looks not appearing now. Also, the code not exists in current code (and jetbrains TerminalView code is also refactored).

So I'll close this issue. Thanks!

**Comment by hverlin** [comment]
I can still reproduce with latest version, but only on Mac. I will try to debug it further later
```java
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at org.jetbrains.plugins.terminal.ShellTerminalWidget.toShellJediTermWidgetOrThrow(ShellTerminalWidget.java:375)
	at org.jetbrains.plugins.terminal.TerminalToolWindowManager.createLocalShellWidget(TerminalToolWindowManager.java:200)
	at com.github.l34130.mise.core.util.TerminalUtils.executeCommand(TerminalUtils.kt:16)
	at com.github.l34130.mise.core.action.MiseRunTaskOnTerminalAction$Companion.executeTask(MiseRunTaskOnTerminalAction.kt:46)
	at com.github.l34130.mise.core.action.MiseRunTaskOnTerminalAction$Companion.executeTask$default(MiseRunTaskOnTerminalAction.kt:34)
	at com.github.l34130.mise.core.toolwindow.nodes.MiseTaskNode.onDoubleClick(MiseTaskNode.kt:45)
	at com.github.l34130.mise.core.toolwindow.MiseTreeToolWindow$4.onDoubleClick(MiseTreeToolWindow.kt:106)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:16)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:63)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6662)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3394)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:479)
	at java.desktop/java.awt.Component.processEvent(Component.java:6427)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5032)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4963)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4577)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4518)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2810)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:755)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:621)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$21(IdeEventQueue.kt:564)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:564)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:117)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by 134130** [comment]
We maybe can use Console interface instead of Terminal.

**Comment by hverlin** [comment]
This is fixed when using the ▶️ icon in a `mise.toml` file. However, it is still broken (only on my mac) when double-clicking on a task name from the sidebar (as this is not using the new configuration)

**Comment by 134130** [comment]
> This is fixed when using the ▶️ icon in the gutter of a `mise.toml` file. However, it is still broken (only on my mac) when double-clicking on a task name from the sidebar (as this is not using the new configuration)

Thank you for your debugging. I'm planning this to migrate to run configuration as RunMarkProvider does it.

I'll close this issue after migration, but I currently take on looking for how can we cache the mise command line result and psi elements on intellij platform.

There are many plugins that contain threading problems, and that's why I'm not on resolving this problem directly.

**Comment by 134130** [comment]
Closing since ShellTerminal action is obsoleted on: #166
