### ISSUE TITLE
Error: DevTool name must be lowercase

### ISSUE THREAD

**Issue by hverlin** [134130/intellij-mise#87]
Using e.g. `cargo:hyperfine` will throw an error and crash the plugin

```
java.lang.IllegalArgumentException: DevTool name must be lowercase
	at com.github.l34130.mise.core.command.MiseDevToolName.constructor-impl(MiseDevToolName.kt:11)
	at com.github.l34130.mise.core.command.MiseCommandLine.loadDevTools(MiseCommandLine.kt:68)
	at com.github.l34130.mise.core.command.MiseCommandLine.loadDevTools$default(MiseCommandLine.kt:19)
	at com.github.l34130.mise.core.setup.AbstractProjectSdkSetup.configureSdk(AbstractProjectSdkSetup.kt:50)
	at com.github.l34130.mise.core.setup.AbstractProjectSdkSetup.runActivity(AbstractProjectSdkSetup.kt:29)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runOldActivity(StartupManagerImpl.kt:340)
```

`:` is not lowercase: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/is-lower-case.html

**Comment by 134130** [comment]
Sorry my bad..

**Comment by 134130** [comment]
@hverlin Thank you for your reporting!!

**Comment by hverlin** [comment]
@134130 Thank you for fixing!

btw, it appears that the marketplace does not list the v2.6.2 version yet
https://plugins.jetbrains.com/plugin/24904-mise

**Comment by 134130** [comment]
> @134130 Thank you for fixing!
> 
> btw, it appears that the marketplace does not list the v2.6.2 version yet [plugins.jetbrains.com/plugin/24904-mise](https://plugins.jetbrains.com/plugin/24904-mise)

@hverlin Yes, I responded it quickly because it is so critical, but JetBrains is still reviewing this. (Maybe they are on holiday)
